package com.frauddetect.starter.model;

/**
 * Holds the plain-English explanation generated by the LLM (Ollama).
 */
public class LlmExplanation {

    private String explanation;

    public LlmExplanation() {
    }

    public LlmExplanation(String explanation) {
        this.explanation = explanation;
    }

    public String getExplanation() {
        return explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }
}